name: MSVC Build Project

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Compile C File
        run: |
          cl.exe cha.c /D UNICODE /D _UNICODE /MD wlanapi.lib dbghelp.lib credui.lib shlwapi.lib /O2 /Fe:WifiTool.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Compiled-Exe-File
          path: WifiTool.exe
