name: MSVC Build Project

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # 載入 Visual Studio 的 cl.exe 編譯環境
      - name: Initialize MSVC Environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Compile C File
        run: |
                   cl.exe cha.c sqlite3.c /D UNICODE /D _UNICODE /MD /O2 /Fe:cha.exe /link wlanapi.lib dbghelp.lib credui.lib shlwapi.lib advapi32.lib crypt32.lib bcrypt.lib shell32.lib



      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cha-Exe-File
          path: cha.exe
